//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Budgets.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Added_investment_strategy_id_to_expense : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "investment_strategy_id",
                schema: "budgets",
                table: "expenses",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_expenses_investment_strategy_id",
                schema: "budgets",
                table: "expenses",
                column: "investment_strategy_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_expenses_investment_strategy_id",
                schema: "budgets",
                table: "expenses");

            migrationBuilder.DropColumn(
                name: "investment_strategy_id",
                schema: "budgets",
                table: "expenses");
        }
    }
}
