//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Budgets.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Banks_and_expense_changes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "bank_id",
                schema: "budgets",
                table: "expenses",
                type: "character varying(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "is_archived",
                schema: "budgets",
                table: "expenses",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "is_archived",
                schema: "budgets",
                table: "expense_types",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "banks",
                schema: "budgets",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_banks", x => x.id);
                });

            migrationBuilder.UpdateData(
                schema: "budgets",
                table: "expense_types",
                keyColumn: "id",
                keyValue: "et_db610449-8a5f-47d0-be6a-ec26e4945375",
                column: "is_archived",
                value: false);

            migrationBuilder.CreateIndex(
                name: "ix_expenses_bank_id",
                schema: "budgets",
                table: "expenses",
                column: "bank_id");

            migrationBuilder.CreateIndex(
                name: "ix_expenses_is_archived",
                schema: "budgets",
                table: "expenses",
                column: "is_archived");

            migrationBuilder.CreateIndex(
                name: "ix_banks_created_at_utc",
                schema: "budgets",
                table: "banks",
                column: "created_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_banks_name",
                schema: "budgets",
                table: "banks",
                column: "name",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_expenses_banks_bank_id",
                schema: "budgets",
                table: "expenses",
                column: "bank_id",
                principalSchema: "budgets",
                principalTable: "banks",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_expenses_banks_bank_id",
                schema: "budgets",
                table: "expenses");

            migrationBuilder.DropTable(
                name: "banks",
                schema: "budgets");

            migrationBuilder.DropIndex(
                name: "ix_expenses_bank_id",
                schema: "budgets",
                table: "expenses");

            migrationBuilder.DropIndex(
                name: "ix_expenses_is_archived",
                schema: "budgets",
                table: "expenses");

            migrationBuilder.DropColumn(
                name: "bank_id",
                schema: "budgets",
                table: "expenses");

            migrationBuilder.DropColumn(
                name: "is_archived",
                schema: "budgets",
                table: "expenses");

            migrationBuilder.DropColumn(
                name: "is_archived",
                schema: "budgets",
                table: "expense_types");
        }
    }
}
