//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Budgets.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class InitialBudgetsEntities : Migration
{
    private static readonly string[] Columns1 = { "id", "created_at_utc", "is_system_defined", "name", "updated_at_utc" };
    private static readonly string[] Columns2 = { "name", "expense_type_id" };

    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "expense_types",
            schema: "budgets",
            columns: table => new
            {
                id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                is_system_defined = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_expense_types", x => x.id);
            });

        migrationBuilder.CreateTable(
            name: "expenses",
            schema: "budgets",
            columns: table => new
            {
                id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                expense_type_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_expenses", x => x.id);
                table.ForeignKey(
                    name: "fk_expenses_expense_types_expense_type_id",
                    column: x => x.expense_type_id,
                    principalSchema: "budgets",
                    principalTable: "expense_types",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            });

        migrationBuilder.InsertData(
            schema: "budgets",
            table: "expense_types",
            columns: Columns1,
            values: new object[] { "et_db610449-8a5f-47d0-be6a-ec26e4945375", new DateTime(2025, 9, 18, 18, 37, 0, 0, DateTimeKind.Utc), true, "Investment", null });

        migrationBuilder.CreateIndex(
            name: "ix_expense_types_name",
            schema: "budgets",
            table: "expense_types",
            column: "name",
            unique: true);

        migrationBuilder.CreateIndex(
            name: "ix_expenses_expense_type_id",
            schema: "budgets",
            table: "expenses",
            column: "expense_type_id");

        migrationBuilder.CreateIndex(
            name: "ix_expenses_name_expense_type_id",
            schema: "budgets",
            table: "expenses",
            columns: Columns2,
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "expenses",
            schema: "budgets");

        migrationBuilder.DropTable(
            name: "expense_types",
            schema: "budgets");
    }
}
