//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Budgets.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Added_monthly_budget : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "monthly_budgets",
                schema: "budgets",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    settlement_period_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    is_draft = table.Column<bool>(type: "boolean", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_monthly_budgets", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "monthly_budget_expenses",
                schema: "budgets",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    monthly_budget_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    expense_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    expense_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    expense_type_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    expense_type_name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    value = table.Column<decimal>(type: "numeric(18,2)", nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_monthly_budget_expenses", x => x.id);
                    table.ForeignKey(
                        name: "fk_monthly_budget_expenses_monthly_budgets_monthly_budget_id",
                        column: x => x.monthly_budget_id,
                        principalSchema: "budgets",
                        principalTable: "monthly_budgets",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budget_expenses_created_at_utc",
                schema: "budgets",
                table: "monthly_budget_expenses",
                column: "created_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budget_expenses_expense_id",
                schema: "budgets",
                table: "monthly_budget_expenses",
                column: "expense_id");

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budget_expenses_expense_type_id",
                schema: "budgets",
                table: "monthly_budget_expenses",
                column: "expense_type_id");

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budget_expenses_monthly_budget_id",
                schema: "budgets",
                table: "monthly_budget_expenses",
                column: "monthly_budget_id");

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budget_expenses_monthly_budget_id_expense_id",
                schema: "budgets",
                table: "monthly_budget_expenses",
                columns: new[] { "monthly_budget_id", "expense_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budgets_created_at_utc",
                schema: "budgets",
                table: "monthly_budgets",
                column: "created_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budgets_is_draft",
                schema: "budgets",
                table: "monthly_budgets",
                column: "is_draft");

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budgets_month_year",
                schema: "budgets",
                table: "monthly_budgets",
                columns: new[] { "month", "year" });

            migrationBuilder.CreateIndex(
                name: "ix_monthly_budgets_settlement_period_id",
                schema: "budgets",
                table: "monthly_budgets",
                column: "settlement_period_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "monthly_budget_expenses",
                schema: "budgets");

            migrationBuilder.DropTable(
                name: "monthly_budgets",
                schema: "budgets");
        }
    }
}
