services:
  viariceco.api:
    container_name: ViaRiceco.Api
    image: ${DOCKER_REGISTRY-}viariceco-api
    build:
      context: .
      dockerfile: ViaRiceco.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      viariceco.seq:
        condition: service_started
      viariceco.database:
        condition: service_started
      viariceco.redis:
        condition: service_started
      viariceco.rabbitmq:
        condition: service_healthy
    networks:
      - viariceco-network
    restart: unless-stopped

  viariceco.seq:
    container_name: ViaRiceco.Seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - ./.containers/seq-data:/data
    networks:
      - viariceco-network
    restart: unless-stopped

  viariceco.database:
    container_name: ViaRiceco.Database
    image: postgres:latest
    environment:
      - POSTGRES_DB=viariceco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres-data:/var/lib/postgresql/data
    networks:
      - viariceco-network
    restart: unless-stopped

  viariceco.redis:
    container_name: ViaRiceco.Redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.containers/redis-data:/data
    networks:
      - viariceco-network
    restart: unless-stopped
    
  viariceco.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ViaRiceco.Jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    networks:
      - viariceco-network
    restart: unless-stopped

  viariceco.rabbitmq:
    container_name: ViaRiceco.RabbitMQ
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.containers/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - viariceco-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

volumes:
  seq-data:
  postgres-data:
  redis-data:
  rabbitmq-data:

networks:
  viariceco-network:
    driver: bridge
