<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NetArchTest.Rules" />
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="FluentAssertions" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ViaRiceco.Modules.Budgets.Application\ViaRiceco.Modules.Budgets.Application.csproj" />
      <ProjectReference Include="..\ViaRiceco.Modules.Budgets.Domain\ViaRiceco.Modules.Budgets.Domain.csproj" />
      <ProjectReference Include="..\ViaRiceco.Modules.Budgets.Infrastructure\ViaRiceco.Modules.Budgets.Infrastructure.csproj" />
      <ProjectReference Include="..\ViaRiceco.Modules.Budgets.Presentation\ViaRiceco.Modules.Budgets.Presentation.csproj" />
    </ItemGroup>

</Project>
