//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddInvestedCashHistoriesToInvestmentStrategy : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddForeignKey(
                name: "fk_invested_cash_histories_investment_strategies_investment_st",
                schema: "portfolios",
                table: "invested_cash_histories",
                column: "investment_strategy_id",
                principalSchema: "portfolios",
                principalTable: "investment_strategies",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_invested_cash_histories_investment_strategies_investment_st",
                schema: "portfolios",
                table: "invested_cash_histories");
        }
    }
}
