//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class Fix_Duplicate_InvestmentId_Foreign_Key : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_purchase_records_investments_investment_id1",
            schema: "portfolios",
            table: "purchase_records");

        migrationBuilder.DropIndex(
            name: "ix_purchase_records_investment_id1",
            schema: "portfolios",
            table: "purchase_records");

        migrationBuilder.DropColumn(
            name: "investment_id1",
            schema: "portfolios",
            table: "purchase_records");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<string>(
            name: "investment_id1",
            schema: "portfolios",
            table: "purchase_records",
            type: "character varying(100)",
            nullable: true);

        migrationBuilder.CreateIndex(
            name: "ix_purchase_records_investment_id1",
            schema: "portfolios",
            table: "purchase_records",
            column: "investment_id1");

        migrationBuilder.AddForeignKey(
            name: "fk_purchase_records_investments_investment_id1",
            schema: "portfolios",
            table: "purchase_records",
            column: "investment_id1",
            principalSchema: "portfolios",
            principalTable: "investments",
            principalColumn: "id");
    }
}
