//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Invested_cash_history : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_investments_investment_strategies_investment_strategy_id1",
                schema: "portfolios",
                table: "investments");

            migrationBuilder.DropIndex(
                name: "ix_investments_investment_strategy_id1",
                schema: "portfolios",
                table: "investments");

            migrationBuilder.DropColumn(
                name: "investment_strategy_id1",
                schema: "portfolios",
                table: "investments");

            migrationBuilder.CreateTable(
                name: "invested_cash",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    investment_strategy_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    monthly_budget_expense_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_invested_cash", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_investment_strategy_id",
                schema: "portfolios",
                table: "invested_cash",
                column: "investment_strategy_id");

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_investment_strategy_id_monthly_budget_expense",
                schema: "portfolios",
                table: "invested_cash",
                columns: new[] { "investment_strategy_id", "monthly_budget_expense_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_monthly_budget_expense_id",
                schema: "portfolios",
                table: "invested_cash",
                column: "monthly_budget_expense_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "invested_cash",
                schema: "portfolios");

            migrationBuilder.AddColumn<string>(
                name: "investment_strategy_id1",
                schema: "portfolios",
                table: "investments",
                type: "character varying(100)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_investments_investment_strategy_id1",
                schema: "portfolios",
                table: "investments",
                column: "investment_strategy_id1");

            migrationBuilder.AddForeignKey(
                name: "fk_investments_investment_strategies_investment_strategy_id1",
                schema: "portfolios",
                table: "investments",
                column: "investment_strategy_id1",
                principalSchema: "portfolios",
                principalTable: "investment_strategies",
                principalColumn: "id");
        }
    }
}
