//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddCurrencyConvertValueToPurchaseRecord : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "currency_convert_value",
                schema: "portfolios",
                table: "purchase_records",
                type: "numeric(18,8)",
                precision: 18,
                scale: 8,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "currency_convert_value",
                schema: "portfolios",
                table: "purchase_records");
        }
    }
}
