//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1861 // Avoid constant arrays as arguments

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations;
    /// <inheritdoc />
    public partial class Create_Portfolios_Database : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "portfolios");

            migrationBuilder.CreateTable(
                name: "currencies",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    code = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_currencies", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "financial_goals",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    parent_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_financial_goals", x => x.id);
                    table.ForeignKey(
                        name: "fk_financial_goals_financial_goals_parent_id",
                        column: x => x.parent_id,
                        principalSchema: "portfolios",
                        principalTable: "financial_goals",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "investment_strategies",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    financial_goal_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    investment_strategy_type_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    uninvested_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_investment_strategies", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "investment_strategy_types",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_investment_strategy_types", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "investments",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    investment_strategy_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    model_portfolio_percentage = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                    current_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    real_portfolio_percentage = table.Column<decimal>(type: "numeric(5,2)", precision: 5, scale: 2, nullable: false),
                    investment_strategy_id1 = table.Column<string>(type: "character varying(100)", nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_investments", x => x.id);
                    table.ForeignKey(
                        name: "fk_investments_investment_strategies_investment_strategy_id",
                        column: x => x.investment_strategy_id,
                        principalSchema: "portfolios",
                        principalTable: "investment_strategies",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_investments_investment_strategies_investment_strategy_id1",
                        column: x => x.investment_strategy_id1,
                        principalSchema: "portfolios",
                        principalTable: "investment_strategies",
                        principalColumn: "id");
                });

            migrationBuilder.CreateTable(
                name: "purchase_records",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    purchase_date = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,8)", precision: 18, scale: 8, nullable: false),
                    price_per_unit = table.Column<decimal>(type: "numeric(18,8)", precision: 18, scale: 8, nullable: false),
                    total_price = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    currency_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    investment_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    investment_id1 = table.Column<string>(type: "character varying(100)", nullable: true),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_purchase_records", x => x.id);
                    table.ForeignKey(
                        name: "fk_purchase_records_investments_investment_id",
                        column: x => x.investment_id,
                        principalSchema: "portfolios",
                        principalTable: "investments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_purchase_records_investments_investment_id1",
                        column: x => x.investment_id1,
                        principalSchema: "portfolios",
                        principalTable: "investments",
                        principalColumn: "id");
                });

            migrationBuilder.CreateIndex(
                name: "ix_currencies_code",
                schema: "portfolios",
                table: "currencies",
                column: "code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_financial_goals_name_parent_id",
                schema: "portfolios",
                table: "financial_goals",
                columns: new[] { "name", "parent_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_financial_goals_parent_id",
                schema: "portfolios",
                table: "financial_goals",
                column: "parent_id");

            migrationBuilder.CreateIndex(
                name: "ix_investment_strategies_financial_goal_id",
                schema: "portfolios",
                table: "investment_strategies",
                column: "financial_goal_id");

            migrationBuilder.CreateIndex(
                name: "ix_investment_strategies_investment_strategy_type_id",
                schema: "portfolios",
                table: "investment_strategies",
                column: "investment_strategy_type_id");

            migrationBuilder.CreateIndex(
                name: "ix_investment_strategy_types_name",
                schema: "portfolios",
                table: "investment_strategy_types",
                column: "name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_investments_investment_strategy_id",
                schema: "portfolios",
                table: "investments",
                column: "investment_strategy_id");

            migrationBuilder.CreateIndex(
                name: "ix_investments_investment_strategy_id1",
                schema: "portfolios",
                table: "investments",
                column: "investment_strategy_id1");

            migrationBuilder.CreateIndex(
                name: "ix_investments_name_investment_strategy_id",
                schema: "portfolios",
                table: "investments",
                columns: new[] { "name", "investment_strategy_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_purchase_records_currency_id",
                schema: "portfolios",
                table: "purchase_records",
                column: "currency_id");

            migrationBuilder.CreateIndex(
                name: "ix_purchase_records_investment_id",
                schema: "portfolios",
                table: "purchase_records",
                column: "investment_id");

            migrationBuilder.CreateIndex(
                name: "ix_purchase_records_investment_id1",
                schema: "portfolios",
                table: "purchase_records",
                column: "investment_id1");

            migrationBuilder.CreateIndex(
                name: "ix_purchase_records_purchase_date",
                schema: "portfolios",
                table: "purchase_records",
                column: "purchase_date");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "currencies",
                schema: "portfolios");

            migrationBuilder.DropTable(
                name: "financial_goals",
                schema: "portfolios");

            migrationBuilder.DropTable(
                name: "investment_strategy_types",
                schema: "portfolios");

            migrationBuilder.DropTable(
                name: "purchase_records",
                schema: "portfolios");

            migrationBuilder.DropTable(
                name: "investments",
                schema: "portfolios");

            migrationBuilder.DropTable(
                name: "investment_strategies",
                schema: "portfolios");
        }
    }
