//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Changed_table_name : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "pk_invested_cash",
                schema: "portfolios",
                table: "invested_cash");

            migrationBuilder.RenameTable(
                name: "invested_cash",
                schema: "portfolios",
                newName: "invested_cash_histories",
                newSchema: "portfolios");

            migrationBuilder.RenameIndex(
                name: "ix_invested_cash_monthly_budget_expense_id",
                schema: "portfolios",
                table: "invested_cash_histories",
                newName: "ix_invested_cash_histories_monthly_budget_expense_id");

            migrationBuilder.RenameIndex(
                name: "ix_invested_cash_investment_strategy_id_monthly_budget_expense",
                schema: "portfolios",
                table: "invested_cash_histories",
                newName: "ix_invested_cash_histories_investment_strategy_id_monthly_budg");

            migrationBuilder.RenameIndex(
                name: "ix_invested_cash_investment_strategy_id",
                schema: "portfolios",
                table: "invested_cash_histories",
                newName: "ix_invested_cash_histories_investment_strategy_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_invested_cash_histories",
                schema: "portfolios",
                table: "invested_cash_histories",
                column: "id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "pk_invested_cash_histories",
                schema: "portfolios",
                table: "invested_cash_histories");

            migrationBuilder.RenameTable(
                name: "invested_cash_histories",
                schema: "portfolios",
                newName: "invested_cash",
                newSchema: "portfolios");

            migrationBuilder.RenameIndex(
                name: "ix_invested_cash_histories_monthly_budget_expense_id",
                schema: "portfolios",
                table: "invested_cash",
                newName: "ix_invested_cash_monthly_budget_expense_id");

            migrationBuilder.RenameIndex(
                name: "ix_invested_cash_histories_investment_strategy_id_monthly_budg",
                schema: "portfolios",
                table: "invested_cash",
                newName: "ix_invested_cash_investment_strategy_id_monthly_budget_expense");

            migrationBuilder.RenameIndex(
                name: "ix_invested_cash_histories_investment_strategy_id",
                schema: "portfolios",
                table: "invested_cash",
                newName: "ix_invested_cash_investment_strategy_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_invested_cash",
                schema: "portfolios",
                table: "invested_cash",
                column: "id");
        }
    }
}
