//<auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class RenameInvestedCashHistoryToInvestedCashRecord : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "invested_cash_histories",
                schema: "portfolios");

            migrationBuilder.CreateTable(
                name: "invested_cash_records",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    investment_strategy_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    monthly_budget_expense_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_invested_cash_records", x => x.id);
                    table.ForeignKey(
                        name: "fk_invested_cash_records_investment_strategies_investment_stra",
                        column: x => x.investment_strategy_id,
                        principalSchema: "portfolios",
                        principalTable: "investment_strategies",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_records_investment_strategy_id",
                schema: "portfolios",
                table: "invested_cash_records",
                column: "investment_strategy_id");

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_records_investment_strategy_id_monthly_budget",
                schema: "portfolios",
                table: "invested_cash_records",
                columns: new[] { "investment_strategy_id", "monthly_budget_expense_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_records_monthly_budget_expense_id",
                schema: "portfolios",
                table: "invested_cash_records",
                column: "monthly_budget_expense_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "invested_cash_records",
                schema: "portfolios");

            migrationBuilder.CreateTable(
                name: "invested_cash_histories",
                schema: "portfolios",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    investment_strategy_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    monthly_budget_expense_id = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_invested_cash_histories", x => x.id);
                    table.ForeignKey(
                        name: "fk_invested_cash_histories_investment_strategies_investment_st",
                        column: x => x.investment_strategy_id,
                        principalSchema: "portfolios",
                        principalTable: "investment_strategies",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_histories_investment_strategy_id",
                schema: "portfolios",
                table: "invested_cash_histories",
                column: "investment_strategy_id");

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_histories_investment_strategy_id_monthly_budg",
                schema: "portfolios",
                table: "invested_cash_histories",
                columns: new[] { "investment_strategy_id", "monthly_budget_expense_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_invested_cash_histories_monthly_budget_expense_id",
                schema: "portfolios",
                table: "invested_cash_histories",
                column: "monthly_budget_expense_id");
        }
    }
}
