// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViaRiceco.Modules.Portfolios.Infrastructure.Database;

#nullable disable

namespace ViaRiceco.Modules.Portfolios.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PortfoliosDbContext))]
    partial class PortfoliosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portfolios")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViaRiceco.Common.Domain.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Common.Domain.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Common.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Common.Domain.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.Currencies.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code");

                    b.ToTable("currencies", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.FinancialGoals.FinancialGoal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_financial_goals");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_financial_goals_parent_id");

                    b.HasIndex("Name", "ParentId")
                        .IsUnique()
                        .HasDatabaseName("ix_financial_goals_name_parent_id");

                    b.ToTable("financial_goals", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.InvestmentStrategies.InvestmentStrategy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FinancialGoalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("financial_goal_id");

                    b.Property<string>("InvestmentStrategyTypeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("investment_strategy_type_id");

                    b.Property<decimal>("UninvestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("uninvested_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_investment_strategies");

                    b.HasIndex("FinancialGoalId")
                        .HasDatabaseName("ix_investment_strategies_financial_goal_id");

                    b.HasIndex("InvestmentStrategyTypeId")
                        .HasDatabaseName("ix_investment_strategies_investment_strategy_type_id");

                    b.ToTable("investment_strategies", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.InvestmentStrategyTypes.InvestmentStrategyType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_investment_strategy_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_investment_strategy_types_name");

                    b.ToTable("investment_strategy_types", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.Investments.Investment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_amount");

                    b.Property<string>("InvestmentStrategyId")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("investment_strategy_id");

                    b.Property<string>("InvestmentStrategyId1")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("investment_strategy_id1");

                    b.Property<decimal>("ModelPortfolioPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("model_portfolio_percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("RealPortfolioPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("real_portfolio_percentage");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_investments");

                    b.HasIndex("InvestmentStrategyId")
                        .HasDatabaseName("ix_investments_investment_strategy_id");

                    b.HasIndex("InvestmentStrategyId1")
                        .HasDatabaseName("ix_investments_investment_strategy_id1");

                    b.HasIndex("Name", "InvestmentStrategyId")
                        .IsUnique()
                        .HasDatabaseName("ix_investments_name_investment_strategy_id");

                    b.ToTable("investments", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.PurchaseRecords.PurchaseRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("currency_id");

                    b.Property<string>("InvestmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("investment_id");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("price_per_unit");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_purchase_records");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_purchase_records_currency_id");

                    b.HasIndex("InvestmentId")
                        .HasDatabaseName("ix_purchase_records_investment_id");

                    b.HasIndex("PurchaseDate")
                        .HasDatabaseName("ix_purchase_records_purchase_date");

                    b.ToTable("purchase_records", "portfolios");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.FinancialGoals.FinancialGoal", b =>
                {
                    b.HasOne("ViaRiceco.Modules.Portfolios.Domain.FinancialGoals.FinancialGoal", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_financial_goals_financial_goals_parent_id");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.Investments.Investment", b =>
                {
                    b.HasOne("ViaRiceco.Modules.Portfolios.Domain.InvestmentStrategies.InvestmentStrategy", null)
                        .WithMany()
                        .HasForeignKey("InvestmentStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investments_investment_strategies_investment_strategy_id");

                    b.HasOne("ViaRiceco.Modules.Portfolios.Domain.InvestmentStrategies.InvestmentStrategy", null)
                        .WithMany("Investments")
                        .HasForeignKey("InvestmentStrategyId1")
                        .HasConstraintName("fk_investments_investment_strategies_investment_strategy_id1");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.PurchaseRecords.PurchaseRecord", b =>
                {
                    b.HasOne("ViaRiceco.Modules.Portfolios.Domain.Investments.Investment", null)
                        .WithMany("PurchaseRecords")
                        .HasForeignKey("InvestmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_records_investments_investment_id");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.InvestmentStrategies.InvestmentStrategy", b =>
                {
                    b.Navigation("Investments");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Portfolios.Domain.Investments.Investment", b =>
                {
                    b.Navigation("PurchaseRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
