<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\ViaRiceco.Common.Application\ViaRiceco.Common.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FastEndpoints" />
      <PackageReference Include="FastEndpoints.AspVersioning" />
    </ItemGroup>

</Project>
