// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViaRiceco.Modules.Accounting.Infrastructure.Database;

#nullable disable

namespace ViaRiceco.Modules.Accounting.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20250917171750_Added_Inbox_Integration_Event_Handler")]
    partial class Added_Inbox_Integration_Event_Handler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accounting")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViaRiceco.Common.Domain.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "accounting");
                });

            modelBuilder.Entity("ViaRiceco.Common.Domain.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "accounting");
                });

            modelBuilder.Entity("ViaRiceco.Common.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "accounting");
                });

            modelBuilder.Entity("ViaRiceco.Common.Domain.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "accounting");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Accounting.Domain.SettlementPeriods.SettlementPeriod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month")
                        .HasAnnotation("CheckConstraint", "Month BETWEEN 1 AND 12");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_settlement_periods");

                    b.HasIndex("Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_settlement_periods_month_year");

                    b.ToTable("settlement_periods", "accounting");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Accounting.Domain.TaxTypes.TaxType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tax_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tax_types_name");

                    b.ToTable("tax_types", "accounting");
                });

            modelBuilder.Entity("ViaRiceco.Modules.Accounting.Domain.SettlementPeriods.SettlementPeriod", b =>
                {
                    b.OwnsMany("ViaRiceco.Modules.Accounting.Domain.Incomes.Income", "Incomes", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("SettlementPeriodId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("settlement_period_id");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_income");

                            b1.HasIndex("SettlementPeriodId")
                                .HasDatabaseName("ix_income_settlement_period_id");

                            b1.ToTable("income", "accounting");

                            b1.WithOwner()
                                .HasForeignKey("SettlementPeriodId")
                                .HasConstraintName("fk_income_settlement_periods_settlement_period_id");
                        });

                    b.OwnsMany("ViaRiceco.Modules.Accounting.Domain.Taxes.Tax", "Taxes", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<string>("SettlementPeriodId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("settlement_period_id");

                            b1.Property<string>("TaxTypeId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("tax_type_id");

                            b1.Property<DateTime?>("UpdatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at_utc");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_tax");

                            b1.HasIndex("SettlementPeriodId")
                                .HasDatabaseName("ix_tax_settlement_period_id");

                            b1.ToTable("tax", "accounting");

                            b1.WithOwner()
                                .HasForeignKey("SettlementPeriodId")
                                .HasConstraintName("fk_tax_settlement_periods_settlement_period_id");
                        });

                    b.Navigation("Incomes");

                    b.Navigation("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
