// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Accounting.Infrastructure.Database.Migrations;

/// <inheritdoc />
public partial class AddIsDraftToSettlementPeriod : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AddColumn<bool>(
            name: "is_draft",
            schema: "accounting",
            table: "settlement_periods",
            type: "boolean",
            nullable: false,
            defaultValue: true);

        migrationBuilder.CreateIndex(
            name: "ix_settlement_periods_is_draft",
            schema: "accounting",
            table: "settlement_periods",
            column: "is_draft");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "ix_settlement_periods_is_draft",
            schema: "accounting",
            table: "settlement_periods");

        migrationBuilder.DropColumn(
            name: "is_draft",
            schema: "accounting",
            table: "settlement_periods");
    }
}
