//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ViaRiceco.Modules.Accounting.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Create_Accounting_Database : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "accounting");

            migrationBuilder.CreateTable(
                name: "settlement_periods",
                schema: "accounting",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    month = table.Column<int>(type: "integer", nullable: false),
                    year = table.Column<int>(type: "integer", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_settlement_periods", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "tax_types",
                schema: "accounting",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tax_types", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "income",
                schema: "accounting",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    value = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    settlement_period_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_income", x => x.id);
                    table.ForeignKey(
                        name: "fk_income_settlement_periods_settlement_period_id",
                        column: x => x.settlement_period_id,
                        principalSchema: "accounting",
                        principalTable: "settlement_periods",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "tax",
                schema: "accounting",
                columns: table => new
                {
                    id = table.Column<string>(type: "text", nullable: false),
                    value = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    tax_type_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    settlement_period_id = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tax", x => x.id);
                    table.ForeignKey(
                        name: "fk_tax_settlement_periods_settlement_period_id",
                        column: x => x.settlement_period_id,
                        principalSchema: "accounting",
                        principalTable: "settlement_periods",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_income_settlement_period_id",
                schema: "accounting",
                table: "income",
                column: "settlement_period_id");

            migrationBuilder.CreateIndex(
                name: "ix_settlement_periods_month_year",
                schema: "accounting",
                table: "settlement_periods",
                columns: new[] { "month", "year" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_tax_settlement_period_id",
                schema: "accounting",
                table: "tax",
                column: "settlement_period_id");

            migrationBuilder.CreateIndex(
                name: "ix_tax_types_name",
                schema: "accounting",
                table: "tax_types",
                column: "name",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "income",
                schema: "accounting");

            migrationBuilder.DropTable(
                name: "tax",
                schema: "accounting");

            migrationBuilder.DropTable(
                name: "tax_types",
                schema: "accounting");

            migrationBuilder.DropTable(
                name: "settlement_periods",
                schema: "accounting");
        }
    }
}
